#!/usr/bin/env python3
"""Generate the LaTeX tables of the large-map BBS study and the ESKF NEES study
from the committed CSVs (docs/paper/data/bbs_largemap.csv, eskf_nees.csv).

    python3 docs/paper/make_study_tables.py          # write the tables
    python3 docs/paper/make_study_tables.py --print  # also print derived stats

check_numbers.py imports this module and fails if the committed tables differ
from what the CSVs produce, so no number in these tables is typed by hand.
"""
import csv
import statistics as st
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
TABLES = ROOT / "arxiv_ref" / "tables"


def p95(xs):
    s = sorted(xs)
    k = 0.95 * (len(s) - 1)
    lo = int(k)
    return s[lo] + (k - lo) * (s[min(lo + 1, len(s) - 1)] - s[lo])


# ---------------------------------------------------------------- BBS large map
def bbs_rows():
    return list(csv.DictReader(open(DATA / "bbs_largemap.csv")))


def bbs_cell(rows, m, s, meth):
    x = [a for a in rows if a["map_m"] == m and a["stratum"] == s and a["method"] == meth]
    ok = [int(a["success"]) for a in x]
    acc = [int(a["accepted"]) for a in x]
    return {
        "n": len(x),
        "succ": sum(ok),
        "acc": sum(acc),
        "fa": sum(1 for o, a in zip(ok, acc) if a and not o),
        "notfree": sum(1 - int(a["rec_free"]) for a in x),
        "lat": st.median(float(a["time_ms"]) for a in x) if x else 0.0,
        "lat95": p95([float(a["time_ms"]) for a in x]) if x else 0.0,
    }


def bbs_stats(rows):
    out = {}
    for m in ["20", "40", "80"]:
        for s in ["in", "out"]:
            for meth in ["old", "new"]:
                c = bbs_cell(rows, m, s, meth)
                if c["n"]:
                    out[(m, s, meth)] = c
    return out


def bbs_table(rows):
    S = bbs_stats(rows)
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{\textbf{Relocalization on large synthetic maps: v0.1 window versus map-sized window.} "
        r"Warehouse-like maps with repeated shelf rows at 0.1\,m/cell; kidnapped poses stratified by whether "
        r"they lie inside (in) or outside (out) the set the v0.1 node searched ($-10$\,m to $+15.5$\,m about the "
        r"map center); the 20\,m map lies entirely inside it. Each cell reads v0.1\,/\,current matcher on identical "
        r"scans (U$[0,0.8]$ beam clutter). Success: position error $<0.5$\,m and yaw error $<10^\circ$; accepted: "
        r"$S_0^\star\ge0.40|\mathcal{E}|$; false accept: accepted but not a success. Latency is the single-threaded "
        r"median (\code{data/bbs\_largemap.csv}, generated by \code{experiments/bbs\_largemap.cpp}).}\label{tab:bbs_large}",
        r"\small",
        r"\begin{tabular}{@{}llrcccr@{}}",
        r"\toprule",
        r"Map & Poses & $N$ & Success & Accepted & False accepts & Median latency (ms) \\",
        r"\midrule",
    ]
    for m in ["20", "40", "80"]:
        for s in ["in", "out"]:
            if (m, s, "old") not in S:
                continue
            o, n = S[(m, s, "old")], S[(m, s, "new")]
            lines.append(
                f"{m}\\,m & {s} & {o['n']} & {o['succ']} / {n['succ']} & {o['acc']} / {n['acc']} & "
                f"{o['fa']} / {n['fa']} & {o['lat']:.0f} / {n['lat']:.0f} \\\\"
            )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def bbs_derived(rows):
    """Aggregates quoted in the text."""
    d = {}
    new = [a for a in rows if a["method"] == "new"]
    old = [a for a in rows if a["method"] == "old"]
    for name, sel in [("new", new), ("old", old)]:
        for m in ["40", "80"]:
            x = [a for a in sel if a["map_m"] == m]
            acc = [a for a in x if a["accepted"] == "1"]
            fa = [a for a in acc if a["success"] == "0"]
            d[f"{name}_{m}_n"] = len(x)
            d[f"{name}_{m}_acc"] = len(acc)
            d[f"{name}_{m}_fa"] = len(fa)
            d[f"{name}_{m}_succ"] = sum(int(a["success"]) for a in x)
        d[f"{name}_notfree"] = sum(1 - int(a["rec_free"]) for a in sel)
    # threshold that would remove every false accept of the current matcher on 40/80 m
    big = [a for a in new if a["map_m"] in ("40", "80")]
    fails = [float(a["score_frac"]) for a in big if a["success"] == "0"]
    rho_star = max(fails)
    d["rho_star"] = rho_star
    d["big_succ"] = sum(int(a["success"]) for a in big)
    d["big_succ_above_rho_star"] = sum(
        1 for a in big if a["success"] == "1" and float(a["score_frac"]) > rho_star
    )
    d["big_n"] = len(big)
    # yaw-flip share among current-matcher false accepts
    fa_new = [a for a in big if a["accepted"] == "1" and a["success"] == "0"]
    d["fa_new_big"] = len(fa_new)
    d["fa_new_flip"] = sum(1 for a in fa_new if float(a["yaw_err_deg"]) > 170)
    d["fa_new_minerr"] = min(float(a["pos_err_m"]) for a in fa_new)
    lat80 = [float(a["time_ms"]) for a in new if a["map_m"] == "80"]
    d["new80_lat_med"] = st.median(lat80)
    d["new80_lat_p95"] = p95(lat80)
    d["new80_lat_max"] = max(lat80)
    return d


# ---------------------------------------------------------------- ESKF NEES
BLOCKS = [("all", r"Full state (15)"), ("p", r"Position $\delta\mathbf{p}$ (3)"),
          ("v", r"Velocity $\delta\mathbf{v}$ (3)"), ("th", r"Attitude $\delta\boldsymbol{\theta}$ (3)"),
          ("ba", r"Accel.\ bias $\delta\mathbf{b}_a$ (3)"), ("bg", r"Gyro bias $\delta\mathbf{b}_g$ (3)")]


def nees_rows():
    r = list(csv.DictReader(open(DATA / "eskf_nees.csv")))
    return r, [x for x in r if float(x["time_s"]) > 0.0]  # epochs after t = 0 (prior)


def nees_stats(rows):
    head, ep = rows
    out = {"runs": int(head[0]["runs"]), "epochs": len(ep)}
    for b, _ in BLOCKS:
        lo = float(head[0]["chi2_lo15" if b == "all" else "chi2_lo3"])
        hi = float(head[0]["chi2_hi15" if b == "all" else "chi2_hi3"])
        for v in ["gi", "rj"]:
            xs = [float(x[f"nees_{b}_{v}"]) for x in ep]
            out[(b, v)] = {
                "lo": lo, "hi": hi, "mean": st.mean(xs), "max": max(xs), "min": min(xs),
                "in": sum(lo <= x <= hi for x in xs), "above": sum(x > hi for x in xs),
                "below": sum(x < lo for x in xs),
            }
    out["maxdiff"] = max(abs(float(x[f"nees_{b}_gi"]) - float(x[f"nees_{b}_rj"]))
                         for x in head for b, _ in BLOCKS)
    return out


def nees_table(rows):
    S = nees_stats(rows)
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        f"\\caption{{\\textbf{{Monte Carlo NEES of the ESKF}} ($N={S['runs']}$ runs, {S['epochs']} epochs at 2\\,Hz "
        r"after $t=0$; initial error and true IMU biases drawn from $\mathbf{P}_0$). Band: two-sided 95\% interval for "
        r"the run-averaged NEES; a consistent filter keeps about 95\% of epochs inside it. In / above / below count "
        r"epochs for the shipped filter ($\mathbf{G}=\mathbf{I}$); the last column is the time-averaged NEES with the "
        r"reset Jacobian enabled on identical data (\code{data/eskf\_nees.csv}, \code{experiments/eskf\_nees.cpp}).}\label{tab:nees}",
        r"\small",
        r"\begin{tabular}{@{}lcccc@{}}",
        r"\toprule",
        r"Error block (dof) & 95\% band & Mean NEES, $\mathbf{G}=\mathbf{I}$ & In / above / below & Mean NEES, reset $\mathbf{G}$ \\",
        r"\midrule",
    ]
    for b, label in BLOCKS:
        g, r = S[(b, "gi")], S[(b, "rj")]
        lines.append(
            f"{label} & [{g['lo']:.2f}, {g['hi']:.2f}] & {g['mean']:.2f} & "
            f"{g['in']} / {g['above']} / {g['below']} & {r['mean']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def generate():
    return {
        TABLES / "bbs_largemap.tex": bbs_table(bbs_rows()),
        TABLES / "eskf_nees.tex": nees_table(nees_rows()),
    }


if __name__ == "__main__":
    for path, text in generate().items():
        path.write_text(text)
        print("wrote", path.relative_to(ROOT))
    if "--print" in sys.argv:
        for k, v in bbs_derived(bbs_rows()).items():
            print("bbs", k, v)
        S = nees_stats(nees_rows())
        for k, v in S.items():
            print("nees", k, v)
